twig:
    default_path: '%kernel.project_dir%/templates'
    globals :
        crudNew: 'info'
        crudBack: 'dark'
        crudDelete: 'danger'
        crudEdit: 'secondary'
        crudShow: 'dark'
        crudSuccess: 'success'

when@test:
    twig:
        strict_variables: true
